theme: jekyll-theme-cayman
title: Apasher's Blog
author: Apasher
description: A site for documentation and general blogging about topics related to capturing retro console games, and playing on CRT displays.
url: https://apasher.github.io

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match

header_pages:
  - archive.html

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header pages:
  - archive.html

home_post_limit: 5

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts
