theme: jekyll-theme-cayman
title: Apasher's Blog
description: A site for general blogging about topics related to capturing retro console games, and playing on CRT displays.

header_pages:
  - archive.html

plugins:
  - jekyll-feed

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

home_post_limit: 5

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts
